repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.89.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=-check
    - id: terraform_tflint
    - id: terrascan
      args:
        - --args=--non-recursive
    - id: terraform_trivy
    - id: terraform_validate
    